name: PlateData
input_channels: 6
n_cond: 1
output_channels: 1
space: 2
composition_seed: 42
shuffling_seed: 42
hparams:
  data_path: data/hyperelasticity/solver_truncation/processed
  metadata_path: null
  val_fraction: 0.05
  test_fraction: 0.05
  budget: 38000  # 200 HF simulations equivalent (200 B_tilde, 1 HF sim = 190 solver iterations)
  hf_only: true
  linearization_col: solver_max_its
  q: 0.95556
  cost_column: solver_max_its
  lambd: null
  lambda_bounds: [-20, 20]
  n_samples_target: 1
  no_conditioning: false
